backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: /content/assets
public_folder: ""

collections:
  - name: "news"
    label: "Blog"
    folder: "content/blog"
    create: true
    media_folder: /content/assets/blogImages
    public_folder: ""
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    extension: "md"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"], editorComponents: ["image"] }
  - name: "orgInfo"
    label: "Organization Info"
    editor:
      preview: false
    files:
      - name: "basic"
        label: "Basic Info"
        file: "content/basics.json"
        media_folder: /content/assets/logo
        public_folder: ""
        fields:
        - { label: "Organization Name", name: "orgName", widget: string }
        - { label: "Organization Logo", name: "orgLogo", widget: image }
        - { label: "Hometown", name: "hometown", widget: string }
      - name: "colors"
        label: "Colors"
        file: "content/colors.json"
        fields:
        - { label: "Primary Color", name: "primaryColor", widget: color }
        - { label: "Secondary Color", name: "secondaryColor", widget: color }
        - { label: "Text Color", name: "textColor", widget: color }
  - name: "teams"
    label: "Teams"
    editor:
      preview: false
    folder: "content/teams"
    create: true
    media_folder: /content/assets/teams
    public_folder: ""
    slug: "{{ageGroup}}"
    format: "json"
    fields:
      - label: "Age Group"
        name: "ageGroup"
        widget: "string"
        hint: "Examples: 14u, 14 & Under, AAA, 12u (Softball)"
      - label: "Team Bio"
        name: "bio"
        widget: "text"
        required: false
        hint: "A short introduction to the team. One paragraph only."
      - name: "schedule"
        label: "Schedule"
        widget: "object"
        collapsed: true
        fields:
        - label: "Weekly Practice Schedule"
          name: "recurringPractices"
          widget: "list"
          minimize_collapsed: true
          label_singular: "weekly practice"
          hint: "These practices will show as recurring every week. This way, you can \"set it and forget it\" if your practices are consistent every week."
          fields:
            - { label: "Day of the Week", name: "day", widget: select, options: ["Sundays", "Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays"]}
            - label: "Address"
              name: "addressObject"
              widget: object
              fields:
                - { label: "Location Name", name: "location", widget: string }
                - { label: "Street Address", name: "streetAddress", widget: string }
                - { label: "City", name: "city", widget: string }
                - { label: "State", name: "state", widget: select, options: [ "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"] }
                - { label: "Zip Code", name: "zipCode", widget: number, min: 10000, max: 99999 }
            - { label: "Start Time", name: "startTime",  widget: select, options: ["12 AM", "12:15 AM", "12:30 AM", "12:45 AM", "1 AM", "1:15 AM", "1:30 AM", "1:45 AM", "2 AM", "2:15 AM", "2:30 AM", "2:45 AM", "3 AM", "3:15 AM", "3:30 AM", "3:45 AM", "4 AM", "4:15 AM", "4:30 AM", "4:45 AM", "5 AM", "5:15 AM", "5:30 AM", "5:45 AM", "6 AM", "6:15 AM", "6:30AM", "6:45 AM", "7 AM", "7:15 AM", "7:30 AM", "7:45 AM", "8 AM", "8:15 AM", "8:30 AM", "8:45 AM", "9 AM", "9:15 AM", "9:30 AM", "9:45 AM", "10 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11 AM", "11:15 AM", "11:30 AM", "11:45 AM", "12 PM", "12:15 PM", "12:30 PM", "12:45 PM", "1 PM", "1:15 PM",  "1:30 PM", "1:45 PM", "2 PM", "2:15 PM", "2:30 PM", "2:45 PM", "3 PM", "3:15 PM", "3:30 PM", "3:45 PM", "4 PM", "4:15 PM", "4:30 PM", "4:45 PM", "5 PM", "5:15 PM", "5:30 PM", "5:45 PM", "6 PM", "6:15 PM", "6:30 PM", "6:45 PM", "7 PM", "7:15 PM", "7:30 PM", "7:45 PM", "8 PM", "8:15 PM", "8:30 PM", "8:45 PM", "9 PM", "9:15 PM", "9:30 PM", "9:45 PM", "10 PM", "10:15 PM", "10:30 PM", "10:45 PM", "11 PM", "11:15 PM", "11:30 PM", "11:45 PM"] }
            - { label: "End Time", name: "endTime", widget: select, options: ["12 AM", "12:15 AM", "12:30 AM", "12:45 AM", "1 AM", "1:15 AM", "1:30 AM", "1:45 AM", "2 AM", "2:15 AM", "2:30 AM", "2:45 AM", "3 AM", "3:15 AM", "3:30 AM", "3:45 AM", "4 AM", "4:15 AM", "4:30 AM", "4:45 AM", "5 AM", "5:15 AM", "5:30 AM", "5:45 AM", "6 AM", "6:15 AM", "6:30AM", "6:45 AM", "7 AM", "7:15 AM", "7:30 AM", "7:45 AM", "8 AM", "8:15 AM", "8:30 AM", "8:45 AM", "9 AM", "9:15 AM", "9:30 AM", "9:45 AM", "10 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11 AM", "11:15 AM", "11:30 AM", "11:45 AM", "12 PM", "12:15 PM", "12:30 PM", "12:45 PM", "1 PM", "1:15 PM",  "1:30 PM", "1:45 PM", "2 PM", "2:15 PM", "2:30 PM", "2:45 PM", "3 PM", "3:15 PM", "3:30 PM", "3:45 PM", "4 PM", "4:15 PM", "4:30 PM", "4:45 PM", "5 PM", "5:15 PM", "5:30 PM", "5:45 PM", "6 PM", "6:15 PM", "6:30 PM", "6:45 PM", "7 PM", "7:15 PM", "7:30 PM", "7:45 PM", "8 PM", "8:15 PM", "8:30 PM", "8:45 PM", "9 PM", "9:15 PM", "9:30 PM", "9:45 PM", "10 PM", "10:15 PM", "10:30 PM", "10:45 PM", "11 PM", "11:15 PM", "11:30 PM", "11:45 PM"] }
        - label: "Upcoming Practices"
          name: "upcomingPractices"
          widget: list
          minimize_collapsed: true
          label_singular: "upcoming practice"
          fields:
            - { label: "Start Time", name: "startTime", widget: datetime, format: "LLLL", picker_utc: "true"}
            - { label: "End Time", name: "endTime", widget: select, options: ["12 AM", "12:15 AM", "12:30 AM", "12:45 AM", "1 AM", "1:15 AM", "1:30 AM", "1:45 AM", "2 AM", "2:15 AM", "2:30 AM", "2:45 AM", "3 AM", "3:15 AM", "3:30 AM", "3:45 AM", "4 AM", "4:15 AM", "4:30 AM", "4:45 AM", "5 AM", "5:15 AM", "5:30 AM", "5:45 AM", "6 AM", "6:15 AM", "6:30AM", "6:45 AM", "7 AM", "7:15 AM", "7:30 AM", "7:45 AM", "8 AM", "8:15 AM", "8:30 AM", "8:45 AM", "9 AM", "9:15 AM", "9:30 AM", "9:45 AM", "10 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11 AM", "11:15 AM", "11:30 AM", "11:45 AM", "12 PM", "12:15 PM", "12:30 PM", "12:45 PM", "1 PM", "1:15 PM",  "1:30 PM", "1:45 PM", "2 PM", "2:15 PM", "2:30 PM", "2:45 PM", "3 PM", "3:15 PM", "3:30 PM", "3:45 PM", "4 PM", "4:15 PM", "4:30 PM", "4:45 PM", "5 PM", "5:15 PM", "5:30 PM", "5:45 PM", "6 PM", "6:15 PM", "6:30 PM", "6:45 PM", "7 PM", "7:15 PM", "7:30 PM", "7:45 PM", "8 PM", "8:15 PM", "8:30 PM", "8:45 PM", "9 PM", "9:15 PM", "9:30 PM", "9:45 PM", "10 PM", "10:15 PM", "10:30 PM", "10:45 PM", "11 PM", "11:15 PM", "11:30 PM", "11:45 PM"] }
            - label: "Address"
              name: "addressObject"
              widget: object
              fields:
                - { label: "Location Name", name: "location", widget: string, options: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]}
                - { label: "Street Address", name: "streetAddress", widget: string }
                - { label: "City", name: "city", widget: string }
                - { label: "State", name: "state", widget: select, options: [ "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"] }
                - { label: "Zip Code", name: "zipCode", widget: number, min: 10000, max: 99999 }
        - label: "Upcoming Games"
          name: "games"
          widget: list
          minimize_collapsed: true
          label_singular: "upcoming game"
          fields:
            - { label: "Start Date & Time", name: "startTime", widget: datetime, format: "LLLL", picker_utc: "true"}
            - { label: "Home or Away?", name: "side", widget: select, options: ["Home", "Away"] }
            - { label: "Opponent", name: "opponent", widget: string }
            - label: "Address"
              name: "addressObject"
              widget: object
              fields:
                - { label: "Location Name", name: "location", widget: string, options: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]}
                - { label: "Street Address", name: "streetAddress", widget: string }
                - { label: "City", name: "city", widget: string }
                - { label: "State", name: "state", widget: select, options: [ "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"] }
                - { label: "Zip Code", name: "zipCode", widget: number, min: 10000, max: 99999 }
      - name: "coaches"
        label: "Coaches"
        widget: list
        minimize_collapsed: true
        fields:
        - {label: "Name", name: "name", widget: string}
        - {label: "Title/Position", name: "title", widget: string}
        - {label: "Image", name: "image", widget: image, required: false, hint: "Optional but highly recommended!" }
        - {label: "Bio", name: "bio", widget: text, required: false, hint: "Optional but highly recommended!" }
      - label: "Show player stats?"
        name: "statsBool"
        widget: boolean
        required: false
      - name: "players"
        label: "Players"
        widget: "list"
        minimize_collapsed: true
        fields:
        - label: "Name"
          name: "name"
          widget: string
        - label: "Use Player Headshot?"
          name: "imgBool"
          widget: boolean
          default: false
        - label: "Player Headshot"
          name: "image"
          widget: image
          required: false
        - label: "Jersey Number"
          name: "jerseyNumber"
          widget: "number"
          value_type: "fart"
          required: false
        - label: "Player's Interests & Hobbies"
          name: "hobbies"
          widget: string
          required: false
        - label: "Favorite Athlete"
          name: "faveAthlete"
          widget: "string"
          required: false
        - label: "Positions"
          name: "positions"
          widget: select
          options: ["P", "C", "INF", "1B", "2B", "3B", "SS", "OF", "LF", "CF", "RF"]
          multiple: true
          required: false
        - label: "Pitching Stats"
          name: "pitchingStats"
          widget: object
          fields:
          - label: "Wins"
            name: "wins"
            widget: number
            valueType: int
            default: 0
          - label: "Losses"
            name: "losses"
            widget: number
            valueType: int
            default: 0
          - label: "ERA"
            name: "era"
            widget: number
            valueType: float
            default: 0
          - label: "Innings Pitched"
            name: "inningsPitched"
            widget: number
            valueType: float
            default: 0
          - label: "Hits"
            name: "hits"
            widget: number
            valueType: int
            default: 0
          - label: "Runs"
            name: "runs"
            widget: number
            valueType: int
            default: 0
          - label: "Earned Runs"
            name: "earnedRuns"
            widget: number
            valueType: float
            default: 0
          - label: "Walks"
            name: "walks"
            widget: number
            valueType: int
            default: 0
          - label: "Strikeouts"
            name: "strikeouts"
            widget: number
            valueType: int
            default: 0
          - label: "Batting Average Against"
            name: "battingAverageAgainst"
            widget: number
            valueType: float
            default: 0
          - label: "WHIP"
            name: "whip"
            widget: number
            valueType: float
            default: 0
        - label: "Hitting Stats"
          name: "hittingStats"
          widget: object
          fields:
          - label: "Games"
            name: "games"
            widget: number
            valueType: int
            default: 0
          - label: "At Bats"
            name: "atBats"
            widget: number
            valueType: int
            default: 0
          - label: "Hits"
            name: "hits"
            widget: number
            valueType: int
            default: 0
          - label: "Home Runs"
            name: "homeRuns"
            widget: number
            valueType: int
            default: 0
          - label: "Triples"
            name: "triples"
            widget: number
            valueType: int
            default: 0
          - label: "Doubles"
            name: "doubles"
            widget: number
            valueType: int
            default: 0
          - label: "Walks"
            name: "walks"
            widget: number
            valueType: int
            default: 0
          - label: "Strikeouts"
            name: "strikeouts"
            widget: number
            valueType: int
            default: 0
          - label: "RBIs"
            name: "rbi"
            widget: number
            valueType: int
            default: 0
          - label: "Batting Average"
            name: "battingAverage"
            widget: number
            valueType: float
            default: 0
  - name: "pages"
    label: "Platform Pages"
    editor:
      preview: false
    files:
    - name: "homePage"
      label: "Home Page"
      file: "content/homePage.json"
      media_folder: /content/assets/homePage
      public_folder: ""
      fields:
      - label: "Header Image"
        name: "heroImage"
        widget: image
      - label: "Header Image Text"
        name: "heroText"
        widget: text
        required: false
      - { label: "Text Below Icons", name: "auxText", widget: text, required: false }
      - { label: "Quote", name: "quotation", widget: text, required: false }
      - { label: "Quote Attribution", name: "quoteAttr", widget: text, required: false }
    - name: "aboutPage"
      label: "About Page"
      file: "content/about.md"
      fields:
      - label: "About Page Body"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"]
        editorComponents: [""]
  - name: "customPages"
    label: "Custom Pages"
    folder: "content/customPages"
    media_folder: /content/assets/customPages
    public_folder: ""
    create: true
    slug: "{{title}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", pattern: ["^.{1,25}$", "Max length is 25 characters"] }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Description", name: "shortDescription", widget: "string", pattern: ["^.{1,35}$", "Max length is 35 characters"] }
      - { label: "Page Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "quote", "bulleted-list", "numbered-list"], editorComponents: ["image"] }
  - name: "gallery"
    label: "Gallery"
    folder: content/gallery
    create: true
    slug: "{{name}}"
    extension: "json"
    media_folder: /content/assets/gallery
    public_folder: ""
    editor:
      preview: false
    fields:
      - label: "Event Name"
        name: "name"
        widget: "string"
      - label: "Event Date"
        name: "datetime"
        widget: "datetime"
        format: "MMM D YYYY"
        dateFormat: "MMM D YYYY"
        timeFormat: false
        pickerUTC: true
      - label: "Images"
        name: "imageList"
        widget: list
        minimize_collapsed: true
        label_singular: "image"
        fields:
          - label: "Image"
            name: "image"
            widget: image
  - name: "siteOptions"
    label: "Site Options"
    editor:
      preview: false
    files:
    - name: "contactInfo"
      label: "Contact Info & Street Address"
      file: "content/siteOptions/contact.json"
      fields:
      - label: "Contact Email"
        name: "email"
        widget: "string"
        hint: "When someone uses a form on your site, this is the address that will receive the email!"
      - label: "Phone Number"
        name: "phoneNumber"
        widget: "string"
        hint: "Make sure to format your phone number! Examples: (949)555-555, 949-555-5555"
      - label: "Address"
        name: "address"
        widget: "object"
        fields:
        - label: "Street Address"
          name: "streetAddress"
          widget: "string"
        - label: "City"
          name: "city"
          widget: "string"
        - label: "State"
          name: "state"
          widget: "select"
          options: [ "AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY" ]
        - label: "Zip Code"
          name: "zipCode"
          widget: "number"
          min: 10000
          max: 99999
    - name: "socials"
      label: "Social Media Accounts"
      file: "content/siteOptions/social.json"
      fields:
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        required: false
        hint: "The full address to your Twitter page! Example: https://twitter.com/your-team"
      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false
        hint: "The full address to your Instagram page! Example: https://instagram.com/your-team"
      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false
        hint: "The full address to your Facebook page! Example: https://facebook.com/your-team"
      - label: "Youtube"
        name: "youtube"
        widget: "string"
        required: false
        hint: "The full address to your Youtube page! Example: https://youtube.com/your-team"